### ISSUE TITLE
Link to xrefmap doesn't work.

### ISSUE THREAD

**Issue by tmonseigne** [NormandErwan/UnityXrefMaps#1]
Hi,
the link : <https://normanderwan.github.io/UnityXrefMaps/xrefmap.yml> 
doesn't work (I have test link to specific version, doesn't work too).
Thibaut

**Comment by NormandErwan** [comment]
Hi Thibaut!
I've just moved the xref maps generation from <https://normanderwan.github.io/DocFxForUnity>. The generation is running, it will be fixed today.

**Comment by NormandErwan** [comment]
The xref maps are online. I'm closing the issue, feel free to re-open it if you still have an issue!

**Comment by tmonseigne** [comment]
It works, thanks
